---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shiny-docker-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shinydocker
    spec:
      containers:
      - name: shinydocker
        image: registry.ng.bluemix.net/shinyapps/shinydocker:mytag
